# Limpieza de datos

La limpieza de datos implica observar más de cerca los problemas en los datos que ha seleccionado incluir en el análisis.

In [1]:
import pandas as pd
import numpy as np

Podemos crear un base de datos (DataFrame):

In [2]:
x = {'Company': ['Ford', 'Ford', 'VW', 'BMW', 'Cooper', 'Cooper'],
     'Stars' : [1, 2, np.nan, 2, 1, 1],
     'Weight' : [2, 4, 2, 2, 3, None],
     'Origin' : ['China', 'Mexico', 'Mexico', None, 'China', np.nan],
     'Length': [40, 50, 30, np.nan, 45, pd.NaT]
}

In [3]:
df  = pd.DataFrame(data = x)
df

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

Guardamos en un archivo CSV (coma separated value)

In [4]:
df.to_csv('data.csv')

In [5]:
%ls # to see the location folders and files

data.csv  drive/  sample_data/

Alternativamente, podemos leer un conjunto de datos ya disponible.

Para que no afecta nuestro base de datos original, podemos copiar base de datos a nueva variable, y trabajamos con estos.

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
%cd /content/drive/MyDrive/Apuntes2039/

/content/drive/MyDrive/Apuntes2039

In [8]:
%mkdir resultados #Creating a folder named -  resultados

mkdir: cannot create directory ‘resultados’: File exists

In [9]:
%cd resultados #moving to this new folder

[Errno 2] No such file or directory: 'resultados #moving to this new folder'
/content/drive/MyDrive/Apuntes2039

In [10]:
%ls #we will see empty folder

011_Input_OutputHistory.ipynb       040_Indexing.ipynb
012_data_types.ipynb                041_multiindex_selection.ipynb
013_arrays.ipynb                    042_Merge_and_Join.ipynb
020_read_iloc_unique_groupby.ipynb  043_hist_scat_violin_count_box.ipynb
021_data_wrangling.ipynb            050_customer_satisfaction.ipynb
022_NumPy_Arrays.ipynb              071_ExploratoryDA.ipynb
030_limpieza.ipynb                  080_regresion.ipynb
031_Missing_Values.ipynb            data.csv
032_pivot_table.ipynb               README.md
033_PivotTables.ipynb               resultados/
034_lambda_pivot_table.ipynb

In [11]:
df.to_csv('data.csv') #saving file data.csv in the default folder, in this case 'resultados'

In [12]:
%ls

011_Input_OutputHistory.ipynb       040_Indexing.ipynb
012_data_types.ipynb                041_multiindex_selection.ipynb
013_arrays.ipynb                    042_Merge_and_Join.ipynb
020_read_iloc_unique_groupby.ipynb  043_hist_scat_violin_count_box.ipynb
021_data_wrangling.ipynb            050_customer_satisfaction.ipynb
022_NumPy_Arrays.ipynb              071_ExploratoryDA.ipynb
030_limpieza.ipynb                  080_regresion.ipynb
031_Missing_Values.ipynb            data.csv
032_pivot_table.ipynb               README.md
033_PivotTables.ipynb               resultados/
034_lambda_pivot_table.ipynb

In [13]:
ndf = df.copy() #saving a copy of df in new variable called ndf

In [14]:
ndf.Length.mean().round(1)

41.2

Para verificar, ¿falta algún dato?:

In [15]:
ndf.isnull().values.any()

True

In [16]:
ndf.isnull().any()

Company    False
Stars       True
Weight      True
Origin      True
Length      True
dtype: bool

alternativamente:

In [17]:
ndf.isna().values.any()

True

In [18]:
ndf.isna().any()

Company    False
Stars       True
Weight      True
Origin      True
Length      True
dtype: bool

In [19]:
ndf.isnull().sum()

Company    0
Stars      1
Weight     1
Origin     2
Length     2
dtype: int64

In [20]:
ndf.isnull().sum().sum()

6

The percentage of the number of missing values of an entire column:

In [21]:
x = (ndf.isnull().sum()/len(ndf)*100).round(2)
x.name='%of missing data'
x

Company     0.00
Stars      16.67
Weight     16.67
Origin     33.33
Length     33.33
Name: %of missing data, dtype: float64

- `Origin` has 33.33% of data missing

In [22]:
type(x) #note that, it is a series data. not a dataframe

pandas.core.series.Series

Count the Total Missing Values per Row

    .sum(axis=1)  -  This method sums the True values (which are treated as 1) across each row.

In [23]:
ndf.isnull().sum(axis=1)

0    0
1    0
2    1
3    2
4    0
5    3
dtype: int64

In [24]:
ndf.isnull().sum(axis=1)/len(df.columns)*100  # df.shape[1]

0     0.0
1     0.0
2    20.0
3    40.0
4     0.0
5    60.0
dtype: float64

In [25]:
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

### Handling the missing values

####  Método 1:

Descartar las observaciones con valores faltantes

In [26]:
ndf = df.copy()

    ndf.dropna()   -  This method is used to remove missing values from a DataFrame.

  By default, it drops any row that contains $at\ least\ one$ missing value.

In [27]:
ndf.dropna(inplace = True)

In [28]:
ndf.isna().values.any()

False

In [29]:
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
4  Cooper    1.0     3.0   China     45

El problema con esta estrategia es que:
- si falta algún dato en todo el conjunto de datos, la fila correspondiente se elimina.

In [30]:
ndf.isna().any()

Company    False
Stars      False
Weight     False
Origin     False
Length     False
dtype: bool

####  Método 2:

Suelte las `columnas` donde falta `al menos` un elemento:

In [31]:
ndf = df.copy()
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

Suelte las `columnas` donde falta al menos un elemento:

In [32]:
ndf.dropna(axis = 1,      # axis 1 is acros the rows
           inplace = True)
ndf

  Company
0    Ford
1    Ford
2      VW
3     BMW
4  Cooper
5  Cooper

####  Método 3:

Suelte las `columnas` donde falta `al menos` un elemento:

In [33]:
ndf = df.copy()
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

Drop the rows where `all elements` are missing.

This method removes rows (or columns, depending on the axis parameter) from the DataFrame ndf where all entries are missing (NaN).

The how='all' parameter specifies that only rows where every value is NaN will be dropped.

In [34]:
ndf.dropna(how='all',
           inplace = True)
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

### Método 4:

    Threshold  - thresh = 2  : `Mantenga` solo las filas con al menos 2 valores que  NO SEAN `NaN`.

In [35]:
ndf = df.copy()
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

In [36]:
ndf.dropna(thresh=4,      # In a row, it needs at least 4 values is needed, to maintain in df
           inplace = True)
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
4  Cooper    1.0     3.0   China     45

Obviously, rows 3 and 5 has only 2 data, since our `thresh = 4` we need `at least 4 non NaN` data to `maintain` the row.

Defina en qué columnas buscar valores faltantes.

In [37]:
ndf = df.copy()
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

In [38]:
ndf.dropna(thresh = 5,  #if there is not 5 nan values, the column will be eliminated
           axis = 1,
           inplace = True
           )
ndf

  Company  Stars  Weight
0    Ford    1.0     2.0
1    Ford    2.0     4.0
2      VW    NaN     2.0
3     BMW    2.0     2.0
4  Cooper    1.0     3.0
5  Cooper    1.0     NaN

Which are the `Rows` with `at least one` missing data ??

In [39]:
ndf = df.copy()
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

In [40]:
missed = ndf.isna().any(axis = 1)
missed

0    False
1    False
2     True
3     True
4    False
5     True
dtype: bool

In [41]:
ndf[missed]

  Company  Stars  Weight  Origin Length
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
5  Cooper    1.0     NaN     NaN    NaT

Para saber mas:

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

#### Solucion 2:

Replace missing values with some other values - Data Imputation

In [42]:
ndf = df.copy()

In [43]:
wm = ndf.Weight.mean()
wm

2.6

In [44]:
ndf['Weight'].fillna(value = wm,
                    inplace = True)
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     2.6     NaN    NaT

[Datos faltantes: dos grandes problemas con la imputación media](https://www.theanalysisfactor.com/mean-imputation/)

In [45]:
ndf['Length'].fillna(value = ndf.Length.median(),
                    inplace = True)
ndf

  Company  Stars  Weight  Origin  Length
0    Ford    1.0     2.0   China    40.0
1    Ford    2.0     4.0  Mexico    50.0
2      VW    NaN     2.0  Mexico    30.0
3     BMW    2.0     2.0    None    42.5
4  Cooper    1.0     3.0   China    45.0
5  Cooper    1.0     2.6     NaN    42.5

In [46]:
mm  = ndf.Origin.mode()
mm

0     China
1    Mexico
Name: Origin, dtype: object

In [47]:
mm[0]

'China'

In [48]:
ndf['Origin'].fillna(value = mm[0], #'NoPais',
                    inplace = True)
ndf

  Company  Stars  Weight  Origin  Length
0    Ford    1.0     2.0   China    40.0
1    Ford    2.0     4.0  Mexico    50.0
2      VW    NaN     2.0  Mexico    30.0
3     BMW    2.0     2.0   China    42.5
4  Cooper    1.0     3.0   China    45.0
5  Cooper    1.0     2.6   China    42.5

In [49]:
ndf.isnull().values.any()

True

In [50]:
ndf = df.copy()
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

Impute particular columns -

In [51]:
ndf.dropna(subset=['Origin', 'Length'],
           inplace = True)
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
4  Cooper    1.0     3.0   China     45

Fill values in each column with favorite operation:

In [52]:
ndf = df.copy()
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

In [53]:
ndf.Origin.mode()[0]

'China'

In [54]:
favs = {'Origin': ndf.Origin.mode()[0],
        'Length': ndf['Length'].mean()
       } # setting a dictionary called favs, in which we saves the favorite values.

In [55]:
ndf.Origin.fillna(favs['Origin'],
                  inplace=True)
ndf.Length.fillna(favs['Length'],
                  inplace=True)
ndf

  Company  Stars  Weight  Origin  Length
0    Ford    1.0     2.0   China   40.00
1    Ford    2.0     4.0  Mexico   50.00
2      VW    NaN     2.0  Mexico   30.00
3     BMW    2.0     2.0   China   41.25
4  Cooper    1.0     3.0   China   45.00
5  Cooper    1.0     NaN   China   41.25

more on `fillna` method : https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html

More on Imputing strategies: https://www.theanalysisfactor.com/seven-ways-to-make-up-data-common-methods-to-imputing-missing-data/

## ¿Cuándo es una mediana mejor en comparación con la media?

In [56]:
data = {'Salary':  [28, 30, 30, 35, 37, 40, 400]
       }
adf = pd.DataFrame(data)
adf

   Salary
0      28
1      30
2      30
3      35
4      37
5      40
6     400

In [57]:
adf.describe()

           Salary
count    7.000000
mean    85.714286
std    138.653903
min     28.000000
25%     30.000000
50%     35.000000
75%     38.500000
max    400.000000

- When there are outliers, it is better to use `median` than `mean`.

### Para seleccionar las columnas de la base de datos, puede usar la siguiente codigos:

In [58]:
ndf = df.copy()
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

** Syntaxis ** de loc & iloc

* loc : If you use, `loc`, use the `names`

> df.`loc` [ row-start:row-end,  column-start:column_end]  



* iloc : If you use, `loc`, use the `indices`

> df.`iloc` [row-start:row-end, column-start:columnEnd]

In [59]:
ndf.columns

Index(['Company', 'Stars', 'Weight', 'Origin', 'Length'], dtype='object')

In [60]:
ndf.columns.sort_values()

Index(['Company', 'Length', 'Origin', 'Stars', 'Weight'], dtype='object')

In [61]:
ndf.loc[2:5 , 'Company':'Origin']  # rows 2 to 5, columns  'Company' to 'Origin'

  Company  Stars  Weight  Origin
2      VW    NaN     2.0  Mexico
3     BMW    2.0     2.0    None
4  Cooper    1.0     3.0   China
5  Cooper    1.0     NaN     NaN

In [62]:
favs = ['Stars', 'Weight', 'Origin']

In [63]:
ndf.loc[2:5 , favs]

   Stars  Weight  Origin
2    NaN     2.0  Mexico
3    2.0     2.0    None
4    1.0     3.0   China
5    1.0     NaN     NaN

In [64]:
ndf.iloc[2:5, [1,2, 3]] # iloc  - so, indices

   Stars  Weight  Origin
2    NaN     2.0  Mexico
3    2.0     2.0    None
4    1.0     3.0   China

In [65]:
ndf.columns

Index(['Company', 'Stars', 'Weight', 'Origin', 'Length'], dtype='object')

In [66]:
for i in ndf.columns:
  print(i)

Company
Stars
Weight
Origin
Length

In [67]:
ndf.head(4)

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN

In [68]:
ndf.Company.unique()

array(['Ford', 'VW', 'BMW', 'Cooper'], dtype=object)

In [69]:
df.groupby(['Company', 'Origin']).size()

Company  Origin
Cooper   China     1
Ford     China     1
         Mexico    1
VW       Mexico    1
dtype: int64

In [70]:
df[['Company', 'Origin']].value_counts()

Company  Origin
Cooper   China     1
Ford     China     1
         Mexico    1
VW       Mexico    1
Name: count, dtype: int64

### Eliminar columns / Cambiar nombre de las columns

In [71]:
ndf

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VW    NaN     2.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

In [72]:
ndf2 = ndf.drop(['Stars', 'Origin',],
                axis = 1)
ndf2

  Company  Weight Length
0    Ford     2.0     40
1    Ford     4.0     50
2      VW     2.0     30
3     BMW     2.0    NaN
4  Cooper     3.0     45
5  Cooper     NaN    NaT

In [73]:
new_names = {'Company' : 'Empresa',
             'Weight': 'Peso'
             }

In [74]:
ndf2.rename(columns = new_names,
            inplace = True)
ndf2

  Empresa  Peso Length
0    Ford   2.0     40
1    Ford   4.0     50
2      VW   2.0     30
3     BMW   2.0    NaN
4  Cooper   3.0     45
5  Cooper   NaN    NaT

## Datos perdidos - Tener en cuenta

* Excluya las filas o características.
* Cumpliméntelas con un valor estimado.

Errores de datos - Utilice recursos lógicos para descubrir errores manuales y corríjalos. O, excluya las características.

Incoherencias de codificación - Decida un esquema de codificación simple y convierta y sustituya los valores.

Metadatos perdidos o erróneos - Examine manualmente los campos sospechosos y compruebe el significado correcto.

# Crear un informe de limpieza de datos


Registrar sus actividades de limpieza de datos es esencial para registrar las modificaciones de los datos.

Los futuros proyectos de minería de datos se beneficiarán de los detalles del trabajo disponible.


Es una excelente idea considerar las siguientes cuestiones cuando genere el informe:


* ¿Qué tipos de ruido se han producido en los datos?
* ¿Qué métodos utiliza para eliminar el ruido?
    - ¿Qué técnicas han demostrado ser eficaces?

* ¿Existen casos o atributos que no se pueden recuperar?
    - Asegúrese de registrar los datos que se han excluido por causas del ruido.

## Pivot Table

In [75]:
pd.pivot_table(df,
               index='Company',
               values=['Stars','Weight'], # will do the average of each a, b, c, d
               aggfunc={'Stars': np.mean, 'Weight': np.sum},
               margins = True,
               margins_name='|*|Grand Total|*|',
               columns = 'Origin'
              )#.head()

<ipython-input-75-bf792d7e10d3>:1: FutureWarning: The provided callable <function mean at 0x7b167a76fd90> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,
<ipython-input-75-bf792d7e10d3>:1: FutureWarning: The provided callable <function sum at 0x7b167a76ee60> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,
<ipython-input-75-bf792d7e10d3>:1: FutureWarning: The provided callable <function mean at 0x7b167a76fd90> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,
<ipython-input-75-bf792d7e10d3>:1: FutureWarning: The provided callable <function sum at 0x7b167a76ee60> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,
<ipython-input-75-bf792d7e10d3>:1: FutureWarning: The provided callable <function mean at 0x7b167a76fd90> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,
<ipython-input-75-bf792d7e10d3>:1: FutureWarning: The provided callable <function sum at 0x7b167a76ee60> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,

                  Stars                          Weight         \
Origin            China Mexico |*|Grand Total|*|  China Mexico
Company
Cooper              1.0    NaN          1.000000    3.0    NaN
Ford                1.0    2.0          1.500000    2.0    4.0
VW                  NaN    NaN               NaN    NaN    2.0
|*|Grand Total|*|   1.0    2.0          1.333333    5.0    4.0


Origin            |*|Grand Total|*|
Company
Cooper                          3.0
Ford                            6.0
VW                              NaN
|*|Grand Total|*|               9.0